# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :beta do
    build_app(scheme: "SampleApp")
  end

  desc "Run both unit and UI tests"
  lane :tests do
    unit_tests
    ui_tests
  end

  desc "Runs all ui tests"
  lane :ui_tests do
    scan(
              devices: ["iPhone 11 Pro Max"],
              only_testing: "SampleAppUITests",
              scheme: "SampleApp",
              clean:true
              )
  end

  desc "Runs all ui tests"
  lane :unit_tests do
    scan(
              devices: ["iPhone 11 Pro Max"],
              only_testing: "SampleAppTests",
              scheme: "SampleApp",
              clean:true
              )
  end
end
